# Generated by Django 5.1.1 on 2024-11-07 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_compensation_department_employee_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='compensation',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.DeleteModel(
            name='Compensation',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
