# Generated by Django 5.1.1 on 2024-09-21 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='Test_blog_publish_68aae6_idx',
            old_name='blog_post_publish_bb7600_idx',
        ),
        migrations.AlterModelTable(
            name='post',
            table='Test_blog',
        ),
    ]
